name: build and deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' && github.event_name == 'push' }} #&& github.head_ref != 'refs/heads/main' }}

    permissions:
      pages: write
      id-token: write
    environment:
      name: deploy
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      NODE_ENV: staging
      OUT_DIR: docs/staging/${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build static staging content
        run: |
          npm install
          npm run build
      - name: Deploy staging to GitHub Pages
        # Build on pushes to branches other than main
        uses: actions/deploy-pages@v4

  deploy_production:
    runs-on: ubuntu-latest
    # Only deploy on pushes to the main branch
    if: false
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
